include: package:flutter_lints/flutter.yaml
linter:
  rules:
    - avoid_print
    - prefer_single_quotes
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule

analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - "example/**"
    - "build/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    lines-of-executable-code: 50
    number-of-parameters: 5
    maximum-nesting-level: 5
    technical-debt:
      threshold: 1
      todo-cost: 50
      ignore-cost: 320
      ignore-for-file-cost: 396
      as-dynamic-cost: 322

  metrics-exclude:
    - test/**

  rules:
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    - prefer-extracting-callbacks
    - prefer-const-border-radius
    - avoid-unused-parameters
    - prefer-extracting-callbacks
    - prefer-single-widget-per-file
    - double-literal-format
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    - avoid-unnecessary-type-casts
    - binary-expression-operand-order
    - avoid-dynamic
    - no-empty-block
    - avoid-missing-enum-constant-in-map
    - double-literal-format
    - no-equal-then-else
    - no-magic-number
    - no-object-declaration
    - prefer-async-await
    - prefer-match-file-name
    - prefer-conditional-expressions
    - prefer-first
    - prefer-last
    - member-ordering:
        alphabetize-by-type: true
        order:
          - public-fields
          - private-fields
          - constructors
  anti-patterns:
    - long-method
    - long-parameter-list
